# Generated by Django 4.1.3 on 2022-11-21 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entrada', 'Income'), ('saida', 'Outcome')], default='entrada', max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='businesses.business')),
            ],
        ),
    ]
